"""post header

Revision ID: 12c43a858a3c
Revises: ac4a8bed6e1a
Create Date: 2017-04-29 13:09:20.704917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12c43a858a3c'
down_revision = 'ac4a8bed6e1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('tactic_pic', sa.String(length=64), nullable=True))
    op.add_column('posts', sa.Column('tactic_url', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'tactic_url')
    op.drop_column('posts', 'tactic_pic')
    # ### end Alembic commands ###
