"""removed few fields from comment db

Revision ID: 16ea76e0bdd0
Revises: 7ae6188bec0b
Create Date: 2017-07-06 20:37:25.713657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16ea76e0bdd0'
down_revision = '7ae6188bec0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments') as batch_op:
        batch_op.drop_column('disabled')
        batch_op.drop_column('body_html')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('body_html', sa.TEXT(), nullable=True))
    op.add_column('comments', sa.Column('disabled', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###
