"""multiple images

Revision ID: 2ef8a797edfb
Revises: 7f7508ef8927
Create Date: 2017-11-15 16:45:06.215799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ef8a797edfb'
down_revision = '7f7508ef8927'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('tactic_pic_1200px', sa.String(length=64), nullable=True))
    op.add_column('posts', sa.Column('tactic_pic_768px', sa.String(length=64), nullable=True))
    op.add_column('posts', sa.Column('tactic_pic_992px', sa.String(length=64), nullable=True))
    op.add_column('posts', sa.Column('tactic_pic_lt768px', sa.String(length=64), nullable=True))
    op.add_column('posts', sa.Column('tactic_url_1200px', sa.String(length=64), nullable=True))
    op.add_column('posts', sa.Column('tactic_url_768px', sa.String(length=64), nullable=True))
    op.add_column('posts', sa.Column('tactic_url_992px', sa.String(length=64), nullable=True))
    op.add_column('posts', sa.Column('tactic_url_lt768px', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'tactic_url_lt768px')
    op.drop_column('posts', 'tactic_url_992px')
    op.drop_column('posts', 'tactic_url_768px')
    op.drop_column('posts', 'tactic_url_1200px')
    op.drop_column('posts', 'tactic_pic_lt768px')
    op.drop_column('posts', 'tactic_pic_992px')
    op.drop_column('posts', 'tactic_pic_768px')
    op.drop_column('posts', 'tactic_pic_1200px')
    # ### end Alembic commands ###
