"""Post db creation

Revision ID: 5132f9af9133
Revises: b08030dc6c95
Create Date: 2017-03-13 10:05:31.629466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5132f9af9133'
down_revision = 'b08030dc6c95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_url', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_url')
    # ### end Alembic commands ###
