"""anonymous fields in comment

Revision ID: 7ae6188bec0b
Revises: 12c43a858a3c
Create Date: 2017-06-01 19:23:39.597069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ae6188bec0b'
down_revision = '12c43a858a3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('anonymous_user_name', sa.String(length=32), nullable=True))
    op.add_column('comments', sa.Column('by_anonymous', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'by_anonymous')
    op.drop_column('comments', 'anonymous_user_name')
    # ### end Alembic commands ###
