"""email, about me field additions

Revision ID: 81976baf78fc
Revises: dcccd0c3ce6d
Create Date: 2017-02-18 01:43:37.225712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81976baf78fc'
down_revision = 'dcccd0c3ce6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('about_me', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('country', sa.String(length=32), nullable=True))
    op.add_column('users', sa.Column('last_seen', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('location', sa.String(length=32), nullable=True))
    op.add_column('users', sa.Column('member_since', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('name', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'name')
    op.drop_column('users', 'member_since')
    op.drop_column('users', 'location')
    op.drop_column('users', 'last_seen')
    op.drop_column('users', 'country')
    op.drop_column('users', 'confirmed')
    op.drop_column('users', 'about_me')
    # ### end Alembic commands ###
