"""gifs field addition

Revision ID: ac4a8bed6e1a
Revises: e2829f14eef5
Create Date: 2017-04-29 11:45:08.486012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac4a8bed6e1a'
down_revision = 'e2829f14eef5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('header', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'header')
    # ### end Alembic commands ###
