"""Addition of via_oauth

Revision ID: e2829f14eef5
Revises: 8d5cb73b4d14
Create Date: 2017-04-23 12:03:40.443290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2829f14eef5'
down_revision = '8d5cb73b4d14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('via_oauth', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'via_oauth')
    # ### end Alembic commands ###
